### ISSUE TITLE
Refund Failure (Sandbox): The card parameter is required

### ISSUE THREAD

**Issue by BrandonJamesBorders** [digital-pros/commerce-authorize#14]
**Describe the bug**
Attempting to refund a transaction through the Craft Commerce CP. Get the following error:

![image](https://user-images.githubusercontent.com/6044898/81060665-e9676380-8ea0-11ea-89aa-e2c296fbf02a.png)
 

**To Reproduce**
1. Place an order through the website or build order through CP.
2. Click on "Capture" in payment details to capture the transaction.
3. Wait for the batch to settle (optional step possibly?). 
4. Return to order, enter refund amount, get the error message.

**Expected behavior**
Refund to be processed as desired.

**Screenshots**
![image](https://user-images.githubusercontent.com/6044898/81061085-ba052680-8ea1-11ea-946f-0652c7d5adb5.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by benlobach** [comment]
Hello @BrandonJamesBorders, the transaction will need to settle before it can be refunded as Authorize.net doesn’t allow transactions to be refunded before settling. 

If you would like to void a transaction instead (but refund where possible), there’s an option in the gateway settings to enable that functionality. It’s not enabled by default because it’s not possible to partially void a transaction. As an example, if you entered $5 in the refund box, but the transactions wasn’t settled, Authorize.net would void the full transaction. When this setting is enabled, refund is always the default, and voiding is the fallback if the transactions has not settled.

If you have additional questions, or you run into this problem after the transaction is settled, let us know and we’ll take a deeper look!

**Comment by BrandonJamesBorders** [comment]
Thank's for the response, @benlobach. 

I'm getting the error on transactions that have settled though too. 

![image](https://user-images.githubusercontent.com/6044898/81095904-a96da400-8ed3-11ea-9aab-56bb315f3022.png)

![image](https://user-images.githubusercontent.com/6044898/81095828-8b07a880-8ed3-11ea-84e4-adb873c35cc3.png)

**Comment by benlobach** [comment]
Are you using Accept.js?

**Comment by BrandonJamesBorders** [comment]
No to Accept.js. Built-in form.

**Comment by BrandonJamesBorders** [comment]
Settings if helpful:
![image](https://user-images.githubusercontent.com/6044898/81097816-6c56e100-8ed6-11ea-9be1-816f68b0c357.png)

**Comment by benlobach** [comment]
Thanks, @BrandonJamesBorders. We'll dig into this a bit further and see what we can find. Stay tuned.

**Comment by BrandonJamesBorders** [comment]
@benlobach Any luck? Switched to live credentials today and am still getting the issue.

**Comment by benlobach** [comment]
@BrandonJamesBorders, we're actively working on a release that corrects this issue. The refund is attempted on the capture, but Authorize.net does not allow payment information to be sent along with the capture request. We plan to have a release that allows refunds on the capture request in the next couple of days. Thanks for checking in!

**Comment by BrandonJamesBorders** [comment]
@benlobach Thanks for the update and your work!

**Comment by benlobach** [comment]
@BrandonJamesBorders, thanks for submitting this issue! Release 1.0.12 (2ee4108a5b8767e41187c6641197f67a2be33609) solves this problem.
