### ISSUE TITLE
Refund failed

### ISSUE THREAD

**Issue by wuhhh** [digital-pros/commerce-authorize#15]
**Describe the bug**
Attempting to refund an order fails with the following message printed to the Info column of the transactions tab:

```
(USD) (1 USD = 1 USD)"},
{ 
  "label":"Gateway Response",
  "type":"response",
  "value":"{
    \"messages\":{
      \"resultCode\":\"Error\",\"message\":{
        \"code\":\"E00003\",\"text\":\"The 
          'AnetApi/xml/v1/schema/AnetApiSchema.xsd:cardNumber' element is invalid - The value 
          XX is invalid according to its datatype 'String' - The actual length is less than the 
          MinLength value.\"
        }
      }
    }"
}]'>
```

I have read that authorize.net refunds cannot be initiated until 24 hours have passed since the order was created. In this case, the order was placed on May 5th and the refund attempted on May 14th.

I tried testing locally with the *Save Payment Sources* checkbox ticked, there was no change and the same issue was present on my local setup using a sandbox account. 

We are using Accept.js

**Screenshots**
![Screenshot 2020-05-18 at 10 18 10](https://user-images.githubusercontent.com/23365549/82196134-3b70a600-98f1-11ea-8013-a542ac0e5bdd.png)
![Screenshot 2020-05-18 at 10 18 40](https://user-images.githubusercontent.com/23365549/82196137-3ca1d300-98f1-11ea-955c-5fbd57d0273e.png)

Initial error was with plugin versions:

commerce 3.0.11
commerce-authorize 1.0.11
craft 3.4.9

Updated to latest and still see the same issue:

commerce 3.0.11 => 3.1.3
commerce-authorize 1.0.11 => 1.0.12
craft 3.4.9 => 3.4.19.1

**Comment by benlobach** [comment]
Thanks, @wuhhh! We're running some tests to see if we can replicate the issue. Because we do have to wait for the transactions to settle, it will take a couple of days to investigate.

**Comment by aryehischechter** [comment]
@benlobach I'm having a similar situation when using your plugin to handle apple pay transaction as well.
In AIMResponse.php around line 176
getCard is called on the request might return an empty card and that empty card is stored so that in AIMRefundRequest.php around line 35 where `$transactionRef->getCard()` is called it returns that fake empty card.

The Omnipay common code's getExpiryDate does basically the following
`gmdate("mY", gmmktime(0, 0, 0, null, 1, null))`
which returns `121999` and that's what is stored as the expiration date for the fake card.

What should be done, IMHO, is on the response the request's card needs to be validated.
If it fails the validation, pull the accountNumber from the response's transactionResponse and possibly store that as the Card.

something like in AIMResponse.php in getTransactionReference:
```
                if ($card = $this->request->getCard()) {
                    if (isset($card->getNumberLastFour())) {
                        $transactionRef->setCard(array(
                            'number' => $card->getNumberLastFour(),
                            'expiry' => $card->getExpiryDate('mY')
                        ));
                    } elseif (isset($body->accountNumber)) {
                        $transactionRef->setCard(array(
                            'number' => substr((string)$body->accountNumber, -4, 4) ?: null,
                            'expiry' => $card->getExpiryDate('mY')
                        ));
                    }
                } elseif ($cardReference = $this->request->getCardReference()) {
                    $transactionRef->setCardReference(new CardReference($cardReference));
                }
```


Otherwise, on the refund request, the card should be validated and then somehow when that fails get the transactionResponse from the Gateway Response (but I couldn't really find how that is done).

**Comment by aryehischechter** [comment]
I now realize that where I would make my change is in the omnipay-authorizenet repo.

**Comment by benlobach** [comment]
@aryehischechter, my apologies for the delayed response! Yes, it's a bit tricky as we can't make changes in the omnipay repository. We're working on a new release that will look up the card number based on the transaction reference (so that it can be refunded), but it probably won't be ready for several more weeks.

**Comment by aryehischechter** [comment]
@benlobach 
When making the payment through Apple Pay, Apple does not provide the expiration date. 
So even if we do get the card number we still can't perform the refund.

Will the new release look up the card number in authorize.net so it could also get the expiration date, or is it only getting the card number from within craft?

The former would solve my problem, the latter would not.

**Comment by benlobach** [comment]
@aryehischechter, ideally, we'll pull everything we can from Authorize, but I'll have to see what comes back. Would you mind sharing the code you're using so we could test it as we build it out? If you'd rather email it, feel free to email us at hello@digitalpros.co.

**Comment by challahan** [comment]
Same error here for refunds. Will keep watching for updates.

{
    "messages": {
        "resultCode": "Error",
        "message": {
            "code": "E00003",
            "text": "The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:cardNumber' element is invalid - The value XX is invalid according to its datatype 'String' - The actual length is less than the MinLength value."
        }
    }
}

**Comment by aryehischechter** [comment]
@benlobach has there been any progress on this?

**Comment by benlobach** [comment]
@aryehischechter, @challahan - As of version 1.5 released this evening, you should be able to refund these transactions now. Let me know if you run into any problems!

**Comment by aryehischechter** [comment]
Hey @benlobach,

We're still having the issue even after updating.

The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:cardNumber' element is invalid - The value XX is invalid according to its datatype 'String' - The actual length is less than the MinLength value.

I took a look at the commits and I can't find where this would have been fixed in the recent updates.

**Comment by benlobach** [comment]
@aryehischechter, we're now looking up the reference for the card number, as seen in the update here:

https://github.com/digital-pros/commerce-authorize/blob/a4880b07787cfc7ea61ee03ec2caf91a5bd4430d/src/gateways/Gateway.php#L486 

Does your response from the transaction you are refunding have a card reference number in the response?

**Comment by aryehischechter** [comment]
@benlobach it seems that our $transaction->type is TYPE_PURCHASE so it doesn't get into the if there

**Comment by benlobach** [comment]
@aryehischechter, if you're refunding through the control panel transaction area, the type should be "TYPE_REFUND."

**Comment by aryehischechter** [comment]
@benlobach sorry, you are correct.

The type was correct, but the form is null.

src/gateways/Gateway.php line 320 calls this function without a form param and therefore won't get into the if because isset($form->customerProfile) will always be falsy.

The full stack trace:
```
Gateway.php:517, digitalpros\commerce\authorize\gateways\Gateway->createRequest()
Gateway.php:320, digitalpros\commerce\authorize\gateways\Gateway->refund()
Payments.php:631, craft\commerce\services\Payments->_refund()
Payments.php:365, craft\commerce\services\Payments->refundTransaction()
OrdersController.php:822, craft\commerce\controllers\OrdersController->actionTransactionRefund()
InlineAction.php:57, call_user_func_array:{/var/www/project/vendor/yiisoft/yii2/base/InlineAction.php:57}()
InlineAction.php:57, yii\base\InlineAction->runWithParams()
Controller.php:157, craft\commerce\controllers\OrdersController->runAction()
Controller.php:178, craft\commerce\controllers\OrdersController->runAction()
Module.php:528, craft\web\Application->runAction()
Application.php:291, craft\web\Application->runAction()
Application.php:559, craft\web\Application->_processActionRequest()
Application.php:270, craft\web\Application->handleRequest()
Application.php:386, craft\web\Application->run()
index.php:28, {main}()
```

**Comment by benlobach** [comment]
@aryehischechter - If you change this line to:

https://github.com/digital-pros/commerce-authorize/blob/a4880b07787cfc7ea61ee03ec2caf91a5bd4430d/src/gateways/Gateway.php#L476

if(in_array($transaction->type, [TransactionRecord::TYPE_REFUND, TransactionRecord::TYPE_CAPTURE], false) && **!isset($form->customerProfile)**) {

Does that correct your problem?

**Comment by benlobach** [comment]
@aryehischechter  - We ran through some pretty extensive testing, but perhaps we missed that conditional since this was a pretty specific scenario. If that fixes it, we're happy to run through testing again. If not, I want to be sure we fix it completely!

**Comment by benlobach** [comment]
@aryehischechter - Just wanted to follow-up to see if this change fixed the problem you're experiencing?

**Comment by AndriiBalaban** [comment]
@benlobach 

![image](https://user-images.githubusercontent.com/7914813/114053474-a6bfbf80-9897-11eb-87e1-a9dfdd8e21fe.png)
1) `!isset($form->customerProfile)` was added
2) `!isset($transactionReference->card, $transactionReference->card->number)` was added on line 487, because card object exists, but number is empty
3) the code crashes on this line because the property  **cardReference** is missing in `$transaction->reference`
4) debug console. if you need more data i'll add to the thread

**Comment by benlobach** [comment]
@AndriiBalaban, @aryehischechter, my apologies for the delay on this request! We have pushed a new version (1.5.1) which should correct the problem for this use case. Let us know if you run into anything else!

**Comment by elivz** [comment]
@benlobach I am getting this error again when trying to process a refund with Commerce Authorize 4.0.8 and Commerce 4.6.3.1. Could your previous fix have gotten reverted at some point along the way?

**Comment by benlobach** [comment]
@elivz - Great to hear from you! I've double-checked, and we haven't made any changes in the request function over the past 3 years after resolving this ticket. Which error are you seeing specifically? Do you see the card details in the transaction response?

**Comment by elivz** [comment]
Hey Ben, the error we are getting (in both production & sandbox mode) is `The \u0027AnetApi\/xml\/v1\/schema\/AnetApiSchema.xsd:cardNumber\u0027 element is invalid - The value XX is invalid according to its datatype \u0027String\u0027 - The actual length is less than the MinLength value.`.

<img width="1408" alt="Screenshot 2024-10-25 at 10 34 00 AM" src="https://github.com/user-attachments/assets/dd09771c-8bc7-493e-b43f-22148825ccf1">

And the original gateway reference for this transaction was: `{"approvalCode":"0R2FOU","transId":"80028074637","card":{"number":null,"expiry":"122023"}}`. I am guessing maybe the null card number is the issue here? Not sure how to change that though.....

Here are our current gateway settings:
```
settings:
  acceptJS: '1'
  apiLoginId: $AUTHORIZE_NET_API_LOGIN_ID
  developerMode: $AUTHORIZE_NET_DEVELOPER_MODE
  disableAcceptData: ''
  duplicateWindow: '120'
  insertForm: ''
  paymentButton: ''
  plans: null
  publicKey: $AUTHORIZE_NET_PUBLIC_KEY
  savePaymentMethods: ''
  savedCardPrefix: ''
  sendCartInfo: false
  transactionKey: $AUTHORIZE_NET_TRANSACTION_KEY
  voidRefunds: ''
```

Let me know if there is any other info that would be helpful!

**Comment by benlobach** [comment]
Hey @elivz - I'm running the same version of Commerce and Commerce Authorize in our staging environment, and I have a transaction very similar to yours that I was able to refund with the same settings. Can you take a look at my original transaction, which was processed in July, and see if there are any key differences from your transaction?

https://share.cleanshot.com/X9vzlRqw

**Comment by elivz** [comment]
Hey @benlobach - sorry for the delay. Just getting back into this project and doing some more testing. I believe the issue is related to being in "Authorize & manual capture" mode. In the createRequest method that you were modifying previous w/r/t this issue, it skips to the [second branch](https://github.com/digital-pros/commerce-authorize/blob/d99fcc854ba46cbb6413dcfdc83cf19ee9166a6c/src/gateways/Gateway.php#L564) of the conditional since the `$transaction` type is "authorize" (even though the transaction had been manually captured in the CP at this point). However, there is also no `$form` set, so it leaves the `$card` as `null`. I haven't gotten deep enough into all the logic to figure out what the solution is, but maybe this will make more sense to you and give you the clue you need?

**Comment by benlobach** [comment]
@elivz - Thanks so much! I have opened a new issue to investigate this issue since it seems to be unrelated to this thread.
