### ISSUE TITLE
Pass Order short number with ID

### ISSUE THREAD

**Issue by BrandonJamesBorders** [digital-pros/commerce-authorize#16]
**Is your feature request related to a problem? Please describe.**
My client is expressing confusion between the order short number being the primary Order Identifier in commerce and only having the Order ID being passed to Authorize.net. 

**Describe the solution you'd like**
Pass the order short number in addition to or instead of the order ID. 

The primary reason being the short number is the most commonly used order identifier in Craft CMS. It is searchable within the CMS (ID is not), customers reference it when calling in, etc.

**Comment by benlobach** [comment]
@BrandonJamesBorders, thanks for the feedback! We'll take a look at adding this as an option in the settings. We are currently using the ID because it can be directly referenced in the URL, and the numeric value is sometimes easier to track when the column is visible in the orders area. 

If you haven't already, you can add the Order ID as a column using the gear icon at the bottom of the order status sidebar. Perhaps that would help alleviate some of the confusion until the setting is added?

**Comment by benlobach** [comment]
@BrandonJamesBorders - As of 1.5, we're now adding the short order reference number to the Invoice number in Authorize.net, so you can use both numbers when referencing transactions now.
