### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by mariovass** [digital-pros/commerce-authorize#4]
Hi do you have subscriptions for CraftCommerce in the pipeline, would be amazing if this was possible with Authorize.NET

https://docs.craftcms.com/commerce/v2/subscriptions.html

**Comment by benlobach** [comment]
@mariovass -- Great question, thanks for asking!  We would love to add subscriptions in the future, but the Authorize.net Omnipay gateway does not currently support it. We are considering building the functionality around the gateway, but it depends on the level of interest we have from the community. 

To get the discussion started -- how important would it be to cancel/update/manage the subscription inside the Craft Commerce installation?

**Comment by mariovass** [comment]
Hey @benlobach thanks for the swift response. I think it would be pretty important. I have seen an increasing demand for selling CBD / Cannabis products in the US and Authorize.NET is one of the only gateways that allow it. If subscriptions where possible it would be a big win.

For some reason i thought it was possible from the docs: https://developer.authorize.net/api/reference/features/recurring_billing.html#Subscription_Status

**Comment by benlobach** [comment]
We have written many integrations that use the Recurring Billing API from Authorize.net, but Craft Commerce uses Omnipay rather than using a direct connection with the Authorize.net API. The Authorize.net Omnipay driver currently supports AIM and CIM functions (charging and storing customer profiles), but doesn't support recurring billing out of the box. When we integrate the subscriptions service, we'll have to work through the Authorize.net API. 

Once the subscription is created in Authorize.net, the details of the subscription can be managed directly within the Authorize.net portal. In this initial version, you would be able to cancel/update/change the subscription from within Authrorize.net. Subscriptions could start in Craft but would then be managed inside Authorize.net. What are your thoughts?

**Comment by johnj24** [comment]
Hey, Ben. Consider me in the market for Authorize.net subscriptions as well, and I think having subscription management within Craft is almost essential. I imagine it would be pretty cumbersome to have two separate dashboards dealing with commerce related items. If it has to be separate to start, but you have concrete plans to bring those powers into Commerce, then I could probably make an exception for a short period.

**Comment by johnj24** [comment]
Hi Ben, checking in again. Any chance something is in the works with subscriptions?

**Comment by benlobach** [comment]
@mariovass, @johnj24 - Good news! Version 1.5 brings subscriptions to the plugin. Check out the documentation, and let me know if you have thoughts or feedback!
