### ISSUE TITLE
Saved Payment with AcceptJs

### ISSUE THREAD

**Issue by keyurshah** [digital-pros/commerce-authorize#9]
Hello,

It looks like when a payment source is saved with AcceptJs, that it does not save the last 4 digits of the card.  Without this, it is hard to figure out which card is used.

Is there a way we can pass the only last 4 digits through when the form is submitted to craft and then reference that when saving the card?  

Thanks

**Comment by benlobach** [comment]
Hello @keyurshah,

Because we do not send payment details back to the server when Accept.js is enabled, we are not able to add the credit card number to the saved payment method during processing. However, you can add a **_description_** field to the payment form which will overwrite the default name and save whatever you enter in that particular field.

You could turn the description field into a hidden field and use Javascript to transfer the last four to the field before the payment method is saved. While running some testing, we found that the description field didn't save as expected during checkout, but that has been addressed in tonight's release.

Let us know if you have any questions!

**Comment by keyurshah** [comment]
Ok perfect! I tried using that description field and it didn’t work
earlier.  This fix seems perfect!

On a side note, does craft allow a mechanism to check for expired cards? I
did not see expiration being saved anywhere.

Thanks

**Comment by benlobach** [comment]
No, it's all managed inside Authorize.net. If the card is expired, Authorize.net won't approve the charge on the stored payment method when they checkout.
